# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Install Hugo, build static file, then push them to this repo again.
  build-and-push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Hugo
        run: sudo apt-get install hugo
      
      - name: Build static files
        run: hugo

      - name: Commit build files
        run: |
          git config --local user.email "github-action-bot@github.com"
          git config --local user.name "github-action-bot"
          git commit -m "Build by bot, commit: ${{github.sha}}" -a
      
      - name: Push to remote
        run: |
          git push origin main
          
          
